remotedbi/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'dbmap.views.index', name='home'),
                       url(r'^tables/', 'dbmap.views.view_tables', name='tables'),
                       url(r'^dbadd/', 'dbmap.views.add_db', name='adddb'),
                       url(r'^fields/', 'dbmap.views.view_fields', name='fields'),
                       url(r'^records/', 'dbmap.views.view_records', name='records'),
    # Examples:
    # url(r'^$', 'remotedbi.views.home', name='home'),
    # url(r'^remotedbi/', include('remotedbi.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

dbmap/models.py
from django.db import models


DB_TYPE = (
    ('SC', 'Select'),
    ('SQ', 'Sqlite'),
    ('MY', 'Mysql'),
)


class Databases(models.Model):
    name = models.CharField(max_length=40, verbose_name='Database Name')
    db_type = models.CharField(max_length=2, choices=DB_TYPE, default='SC', verbose_name='Database Type')
    user = models.CharField(max_length=20, verbose_name='Database UserName')
    passwd = models.CharField(max_length=20, verbose_name='Database Password')
    host = models.CharField(max_length=40, verbose_name="Host")


class TablesData(models.Model):
    db = models.ForeignKey(Databases)
    name = models.CharField(max_length=40)
    row_count = models.IntegerField()
    column_count = models.IntegerField()
    decription = models.TextField()


class FieldData(models.Model):
    table = models.ForeignKey(TablesData)
    name = models.CharField(max_length=40)
    data_type = models.CharField(max_length=20)
    nullable = models.BooleanField()
    primary_key = models.BooleanField()
    foreign_key = models.BooleanField()
    decription = models.TextField()


class RecordData(models.Model):
    table = models.ForeignKey(TablesData)
    record = models.TextField()

dbmap/forms.py
#!/usr/bin/env python
from django import forms
from django.forms import ModelForm
from dbmap.models import Databases, DB_TYPE


class DatabaseForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    type = forms.CharField(max_length=2, widget=forms.Select(choices=DB_TYPE), required=False)
    user = forms.CharField(max_length=100, required=False)
    passwd = forms.CharField(max_length=100, widget=forms.PasswordInput(), required=False)
    host = forms.CharField(max_length=40)
    path = forms.FileField(required=False)

dbmap/views.py
from django.shortcuts import render_to_response, RequestContext, HttpResponseRedirect
from urllib import quote_plus as urlquote, unquote
from sqlalchemy.engine import create_engine
from sqlalchemy import orm
from sqlalchemy import *
from sqlalchemy.sql import *
from dbmap.models import TablesData, Databases, FieldData, RecordData
from dbmap.forms import DatabaseForm
import os
import sys
from upload import upload_handle
from save_table import save_field, save_record


def index(request):
    databases = Databases.objects.all()
    context = {'databases': databases}
    return render_to_response('index.html', context, context_instance=RequestContext(request))


def add_db(request):
    form = DatabaseForm()
    context = {'form': form}
    if request.method == 'POST':
        form = DatabaseForm(request.POST)
        db = request.POST['name']
        host = request.POST['host']
        name = request.POST['user']
        passwd = request.POST['passwd']
        db_type = request.POST['type']
        if 'SQ' in request.POST['type']:
            path = request.FILES['path']
            path = upload_handle(path)
            strd = 'sqlite:///%s' % path
        else:
            strd = 'mysql://%s:%s@%s/%s' % (urlquote(name), urlquote(passwd), urlquote(host), urlquote(db))
        ##return render_to_response('database.html', context, context_instance=RequestContext(request))
        messages = []
        metadata = MetaData()
        #strd = 'mysql://%s:%s@%s/%s' % (urlquote(name), urlquote(passwd), urlquote(host), urlquote(db))
        engine = create_engine(strd)
        Session = orm.sessionmaker(bind=engine)
        session = Session()
        connection = engine.connect()
        tab = []
        instance = Databases(name=db, db_type=db_type, user=name, passwd=passwd, host=host)
        instance.save()
        print engine.table_names()
        for t in engine.table_names():
            print t
            tab.append(t)
            messages = Table(t, metadata, autoload=True, autoload_with=engine)
            s = messages.select()
            result = connection.execute(s)
            #print result
            tb = TablesData(db=instance, name=t, row_count=session.query(messages).count(), column_count=len(messages.columns.items()), decription='')
            tb.save()
            save_field(messages, tb)
            save_record(messages, tb, session)
        return HttpResponseRedirect('/')
    return render_to_response('database.html', context, context_instance=RequestContext(request))


def view_fields(request):
    value = 0
    if request.method == 'POST':
        id_data = request.POST['database']
        value = id_data
        databases = Databases.objects.get(pk=id_data)
        print databases.name
        tables = databases.tablesdata_set.all()
        fields = FieldData.objects.all()
        databases = Databases.objects.all()
    else:
        fields = FieldData.objects.all()
        tables = TablesData.objects.all()
        databases = Databases.objects.all()
    context = {'fields': fields, 'tables': tables, 'i': 0, 'databases': databases, 'value': value}
    return render_to_response('fields.html', context, context_instance=RequestContext(request))


def view_records(request):
    value = 0
    if request.method == 'POST':
        id_data = request.POST['database']
        value = id_data
        databases = Databases.objects.get(pk=id_data)
        print databases.name
        tables = databases.tablesdata_set.all()
        records = RecordData.objects.all()
        databases = Databases.objects.all()
    else:
        records = RecordData.objects.all()
        tables = TablesData.objects.all()
        databases = Databases.objects.all()
    context = {'records': records, 'tables': tables, 'i': 0, 'databases': databases, 'value': value}
    return render_to_response('records.html', context, context_instance=RequestContext(request))


def view_tables(request):
    tables = TablesData.objects.all()
    context = {'tables': tables}
    return render_to_response('tables.html', context, context_instance=RequestContext(request))

dbmap/templates/base.html
<!DOCTYPE HTML >
<html lang="en-us">
<head>
    <title>Database Scraping</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">

    <link rel="stylesheet" href="/static/jquery/ui-lightness/jquery-ui-1.10.2.custom.css" />
    <script src="/static/jquery/jquery-1.9.1.js"></script>
    <script src="/static/jquery/jquery-ui-1.10.1.custom.min.js"></script>
    <script src="/static/jquery/jquery.validate.js"></script>
    <link rel="stylesheet" href="/static/css/styles.css">
    <style>
        .error{
            color: #bd4247;
        }
    </style>
    {% block extra_head %}{% endblock %}
</head>
<body>
<div class="wrapper">
    <div class="navbar ">
        <div class="navbar-inner ">
            <div class="container ">
                <a class='brand' href='#'>Database Scraping</a>
                </li>
                </ul>
                <ul class="nav pull-right">
                    <!-- Admin menu here -->
                    <li class=""><a href="/">Database</a></li>
                    <li class=""><a href="/tables/">Tables</a></li>
                    <li class=""><a href="/records/">Records</a></li>
                    <li class=""><a href="/fields/">Fields</a></li>
                    <li class=""></li>





                </ul>

            </div>
        </div>
    </div>



    {% block content %}{% endblock %}
</div>
<footer>
  Database Scraping
</footer>
</body>
</html>

dbmap/templates/database.html
{% extends 'base.html' %}
{% block title %}
    <title >Database Scraping</title>
{% endblock title %}
{% block extra_head %}


{% endblock extra_head %}
{% block content %}

      <div class="container">

        <div id="notifications">
        </div>

        
        <div class="row">
            <div class="span12 ">


                <div id="simple-search-form">
                    <form  action="/dbadd/" enctype="multipart/form-data" method='post' class="well form-search upform" id="shipment_search" ><div style="margin:0;padding:0;display:inline"></div>
                            {% csrf_token %}
                             {% if form.errors %} <p class="errorlist">Please correct the errors below</p> {% endif %}
              
                          
          <div class="control-group">
            
            <div class="controls">
              <label class="control-label" for="id_name">Name:</label>
              <input type="text" class="input-xlarge" id="id_name" name="name">
              
            </div>
          </div>
            <div class="control-group">
            
            <div class="controls">
              <label class="control-label" for="id_type">Database type:</label>
              <select  id="id_type" name="type">
                <option value='SC'>-Select-</option>
                <option value='SQ'>Sqlite</option>
                <option value='MY'>Mysql</option>
              </select>
              
            </div>
          </div>
            <div class="control-group">
            
            <div class="controls">
              <label class="control-label" for="id_user">Database User:</label>
              <input type="text" class="input-xlarge" id="id_user" name="user">
              
            </div>
          </div>
            <div class="control-group">
            
            <div class="controls">
              <label class="control-label" for="id_passwd">Database Password:</label>
              <input type="password" class="input-xlarge" id="id_passwd" name="passwd">
              
            </div>
          </div>
            <div class="control-group">
            
            <div class="controls">
              <label class="control-label" for="id_host">Host:</label>
              <input type="text" class="input-xlarge" id="id_host" name="host">
              
            </div>
          </div>
            <div class="control-group">
            
            <div class="controls">
              <label class="control-label" for="id_path">Path:</label>
              <input type="file" class="input-xlarge" id="id_path" name='path'>
              
            </div>
          </div>
                            <br><button type="submit" class="btn" >Submit</button> &nbsp;&nbsp;

                    </form>
                    <script>
                        $(document).ready(function(){
                            $("#shipment_search").validate({
                                               rules: {
                                                  user: "required",
                                                  passwd: "required",
                                                  name: "required",
                                                  host: "required",
                                                  type: {
                                                      selectcheck: true
                                                    },
                                                  path: "required"
                                               }
                                              });
                            jQuery.validator.addMethod('selectcheck', function (value) {
                              
        return (value != 'SC');
    }, "This field is required");
                            $("#id_type").change(function(){
                                if (this.value=='SQ') {
                                    $('#id_path').closest('.control-group').show()
                                    $('#id_user').closest('.control-group').hide()
                                    $('#id_passwd').closest('.control-group').hide()
                                    $('#id_host').closest('.control-group').hide()
                                }
                                else{
                                    $('#id_path').closest('.control-group').hide()
                                    $('#id_user').closest('.control-group').show()
                                    $('#id_passwd').closest('.control-group').show()
                                    $('#id_host').closest('.control-group').show()
                                }
                            })
                        })
                    </script>

                </div>

<style>
  .marg_data{
    margin-left: 91px;
  }
  .controls{
    width:50%;
  }
  .input-xlarge,#id_type{
    float: right;
  }
</style>
                

            </div>
        </div>
    </div>


{% endblock content %}

dbmap/templates/fields.html
{% extends 'base.html' %}
{% block title %}
    <title >OZZMAP</title>
{% endblock title %}
{% block extra_head %}


{% endblock extra_head %}
{% block content %}
{% load increment_filter %}
      <div class="container">

        <div id="notifications">
        </div>

        <ul class="breadcrumb">
            <li class='active'>Fields</li>

        </ul>

        <div class="row">
            <div class="span12 ">


                <div id="simple-search-form">
                    
                        <span>&nbsp;&nbsp;</span>
                        <form id='field_db' class="well form-search upform" action='/fields/' method='post' name='field_data'>
                        {% csrf_token %}
                        <select name='database' id='database'>
                            <option value=0>--select database--</option>
                            {% for d in databases%}
                            <option value="{{d.id}}">{{d.name}}</option>
                            {% endfor %}
                        </select>

                    </form>

                <script>
                    $(document).ready(function(){
                        $("#database").val({{ value }})
                        $("#database").change(function(){
                            $("#field_db").trigger('submit')
                        
                        })
                        $("#field_db").submit(function(){})
                    })
                </script>
                </div>



            {% for t in tables %}
                
                <table style="width:50%" class="table table-bordered">
                    
                    <tr>
                        <th style="width:5px;" > #</th>
                        <th>Table Name</th>
                        <th>Field Name</th>
                        <th>Field Type</th>
                        <th>Field Nullable</th>
                        <th>Field Primary_key</th>
                        <th>Field Foriegn_key</th>
                        <th>Field Description</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
{% for field in fields %}
                    {% if t.name == field.table.name %}
        
                    <tr>
                        <td >{% increment i %}{{i}} <span class="{{ t.name}}">&nbsp;&nbsp;&nbsp;&nbsp; </span> </td>
                        <td> {{t.name}} </td>
                        <td> {{ field.name}} </td>
                        <td>  {{ field.data_type }}  </td>
                        <td>  {{ field.nullable }} </td>
                        <td>  {{ field.primary_key }}  </td>
                        <td>  {{ field.foreign_key }}  </td>
                        <td>  {{ field.description }}  </td>
                        <td style="width:100px;"><a href="/detail/{{ shipment.id }}" class="btn btn-mini">Details</a></td>
                        <td> <a href="/edit/{{ shipment.id }}" class="btn btn-mini btn-info" rel="nofollow">Edit</a></td>
                        <td> <a href="/delete/{{ shipment.id }}" class="btn btn-mini btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Delete</a> </td>

                    </tr>
                    {% endif %}
        {% endfor %}
      
                    <div class="alert alert-block alert-info">

                       {{t.name}}
                    </div>
      
                </table>
                
 
  {% endfor %}
                <br />


                <style>
                    .ship_status li {list-style: none;float: left;padding:0px 0px 0px 65px;font-weight:bold;font-size:13px;}
                    .ship_status li a{color:#333;}
                </style>



            </div>
        </div>
    </div>


{% endblock content %}

dbmap/templates/index.html
{% extends 'base.html' %}
{% block title %}
    <title >Database Scraping</title>
{% endblock title %}
{% block extra_head %}


{% endblock extra_head %}
{% block content %}

      <div class="container">

        <div id="notifications">
        </div>

        <ul class="breadcrumb">
            <li class='active'>Database</li>

        </ul>

        <div class="row">
            <div class="span12 ">


                <div id="simple-search-form">
                    <form  action="/search/" class="well form-search upform" id="shipment_search" ><div style="margin:0;padding:0;display:inline"></div>

                            <input class="input-medium search-query"  size="30" style="width:220px;" type="text" name="query"/>
                            <button type="submit" class="btn" >Search</button> &nbsp;&nbsp;

                        <span>&nbsp;&nbsp;</span>
                        <a href="/dbadd/" class="btn btn-primary pull-right">Add Database</a>


                    </form>


                </div>


        {% if databases %}
                <table class="table table-striped">
                    <tr>
                        <th style="width:5px;" > </th>
                        <th>Database Name</th>
                        <th>User</th>
                        <th>Host</th>
                        <th>Database Type</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>

        {% for database in databases %}
                    <tr>
                        <td > <span class="{{ database.name}}">&nbsp;&nbsp;&nbsp;&nbsp; </span> </td>
                        <td> {{database.name}} </td>
                        <td> {{ database.user}} </td>
                        <td>  {{ database.host }}  </td>
                        <td>  {{ database.get_db_type_display }} </td>
                        <td style="width:100px;"><a href="/detail/{{ shipment.id }}" class="btn btn-mini">Details</a></td>
                        <td> <a href="/edit/{{ shipment.id }}" class="btn btn-mini btn-info" rel="nofollow">Edit</a></td>
                        <td> <a href="/delete/{{ shipment.id }}" class="btn btn-mini btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Delete</a> </td>

                    </tr>
         {% endfor %}
      {% else %}
                    <div class="alert alert-block alert-info">

                       No Databases yet, add using button above
                    </div>
       {% endif %}
                </table>

                <br />


                <style>
                    .ship_status li {list-style: none;float: left;padding:0px 0px 0px 65px;font-weight:bold;font-size:13px;}
                    .ship_status li a{color:#333;}
                </style>



            </div>
        </div>
    </div>


{% endblock content %}

dbmap/templates/records.html
{% extends 'base.html' %}
{% block title %}
    <title >OZZMAP</title>
{% endblock title %}
{% block extra_head %}


{% endblock extra_head %}
{% block content %}
{% load increment_filter %}
      <div class="container">

        <div id="notifications">
        </div>

        <ul class="breadcrumb">
            <li class='active'>Records</li>

        </ul>

        <div class="row">
            <div class="span12 ">


                <div id="simple-search-form">
                    
                        <span>&nbsp;&nbsp;</span>
                        <form id='field_db' class="well form-search upform" action='/records/' method='post' name='field_data'>
                        {% csrf_token %}
                        <select name='database' id='database'>
                            <option value=0>--select database--</option>
                            {% for d in databases%}
                            <option value="{{d.id}}">{{d.name}}</option>
                            {% endfor %}
                        </select>

                    </form>

                <script>
                    $(document).ready(function(){
                        $("#database").val({{ value }})
                        $("#database").change(function(){
                            $("#field_db").trigger('submit')
                        
                        })
                        $("#field_db").submit(function(){})
                    })
                </script>
                </div>



            {% for t in tables %}
                
                <table style="width:50%" class="table table-bordered">
                    
                    <tr>
                        <th style="width:5px;" > #</th>
                        <th>Database Name</th>
                        <th>Table Name</th>
                        <th>Record</th>
                    </tr>
{% for record in records %}
                    {% if t.name == record.table.name %}
        
                    <tr>
                        <td >{% increment i %}{{i}} <span class="{{ t.name}}">&nbsp;&nbsp;&nbsp;&nbsp; </span> </td>
                        <td> {{t.name}} </td>
                        <td> {{ t.db}} </td>
                        <td>  {{ record.record }}  </td>

                    </tr>
                    {% endif %}
        {% endfor %}
      
                    <div class="alert alert-block alert-info">

                       {{t.name}}
                    </div>
      
                </table>
                
 
  {% endfor %}
                <br />


                <style>
                    .ship_status li {list-style: none;float: left;padding:0px 0px 0px 65px;font-weight:bold;font-size:13px;}
                    .ship_status li a{color:#333;}
                </style>



            </div>
        </div>
    </div>


{% endblock content %}

dbmap/templates/tables.html
{% extends 'base.html' %}
{% block title %}
    <title >Database Scraping</title>
{% endblock title %}
{% block extra_head %}


{% endblock extra_head %}
{% block content %}

      <div class="container">

        <div id="notifications">
        </div>

        <ul class="breadcrumb">
            <li class='active'>Tables</li>

        </ul>

        <div class="row">
            <div class="span12 ">


                <div id="simple-search-form">
                    <form  action="/search/" class="well form-search upform" id="shipment_search" ><div style="margin:0;padding:0;display:inline"></div>

                            <input class="input-medium search-query"  size="30" style="width:220px;" type="text" name="query"/>
                            <button type="submit" class="btn" >Search</button> &nbsp;&nbsp;

                        <span>&nbsp;&nbsp;</span>


                    </form>


                </div>


        {% if tables %}
                <table class="table table-striped">
                    <tr>
                        <th style="width:5px;" > </th>
                        <th>Database Name</th>
                        <th> Table Name</th>
                        <th>No of rows</th>
                        <th>No of Columns</th>
                        <th>Description</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>

        {% for table in tables %}
                    <tr>
                        <td > <span class="{{ table.name}}">&nbsp;&nbsp;&nbsp;&nbsp; </span> </td>
                        <td> {{table.db.name}} </td>
                        <td> {{ table.name}} </td>
                        <td>  {{ table.row_count }}  </td>
                        <td>  {{ table.column_count }} </td>
                        <td>  {{ table.description }}  </td>
                        <td style="width:100px;"><a href="/detail/{{ shipment.id }}" class="btn btn-mini">Details</a></td>
                        <td> <a href="/edit/{{ shipment.id }}" class="btn btn-mini btn-info" rel="nofollow">Edit</a></td>
                        <td> <a href="/delete/{{ shipment.id }}" class="btn btn-mini btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Delete</a> </td>

                    </tr>
         {% endfor %}
      {% else %}
                    <div class="alert alert-block alert-info">

                       No Tables yet, add Database
                    </div>
       {% endif %}
                </table>

                <br />


                <style>
                    .ship_status li {list-style: none;float: left;padding:0px 0px 0px 65px;font-weight:bold;font-size:13px;}
                    .ship_status li a{color:#333;}
                </style>



            </div>
        </div>
    </div>


{% endblock content %}